x-build-args: &build_args
    INSTALL_PYTHON_VERSION: "3.13.3"

x-default-volumes: &default_volumes
    volumes:
        - ./:/app
        - C:/VIDA/jboss/standalone/deployments/VidaEar.ear/VidaWeb.war/WEB-INF/classes:/xsl

x-db-paths: &db_paths
    VIDA_ACCESS_DB_URI: "mssql+pyodbc://${VIDA_DB_USER}:${VIDA_DB_PASS}@host.docker.internal/AccessServer?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_BASEDATA_DB_URI: "mssql+pyodbc://${VIDA_DB_USER}:${VIDA_DB_PASS}@host.docker.internal/basedata?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_CARCOM_DB_URI: "mssql+pyodbc://${VIDA_DB_USER}:${VIDA_DB_PASS}@host.docker.internal/carcom?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_DIAG_DB_URI: "mssql+pyodbc://${VIDA_DB_USER}:${VIDA_DB_PASS}@host.docker.internal/DiagSwdlRepository?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_SESSION_DB_URI: "mssql+pyodbc://${VIDA_DB_USER}:${VIDA_DB_PASS}@host.docker.internal/DiagSwdlSession?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_TIMING_DB_URI: "mssql+pyodbc://${VIDA_DB_USER}:${VIDA_DB_PASS}@host.docker.internal/DiceTiming?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_EPC_DB_URI: "mssql+pyodbc://${VIDA_DB_USER}:${VIDA_DB_PASS}@host.docker.internal/epc?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_IMAGES_DB_URI: "mssql+pyodbc://${VIDA_DB_USER}:${VIDA_DB_PASS}@host.docker.internal/ImageRepository?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_SERVICE_DB_URI: "mssql+pyodbc://${VIDA_DB_USER}:${VIDA_DB_PASS}@host.docker.internal/servicerep_en-US?driver=ODBC+Driver+17+for+SQL+Server"

services:
    vida-db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: vida-db
        restart: always
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "VidaFlask.123"
        ports:
            - 1433:1433
        volumes:
            - sqlserverdata:/var/opt/mssql
            - C:/VIDA/db:/vida

    flask-dev:
        build:
            context: .
            target: development
            args:
                <<: *build_args
        image: openvida-development
        ports:
            - 5000:5000
        environment:
            FLASK_ENV: development
            FLASK_DEBUG: 1
            LOG_LEVEL: debug
            GUNICORN_WORKERS: 4
            <<: *db_paths
        depends_on:
            - vida-db
        <<: *default_volumes

    flask-prod:
        build:
            context: .
            target: production
            args:
                <<: *build_args
        image: openvida-production
        restart: always
        ports:
            - 5000:5000
        environment:
            FLASK_ENV: production
            FLASK_DEBUG: 0
            LOG_LEVEL: info
            GUNICORN_WORKERS: 4
            <<: *db_paths
        depends_on:
            - vida-db
        <<: *default_volumes

    manage:
        build:
            context: .
            target: development
            args:
                <<: *build_args
        entrypoint: flask
        environment:
            FLASK_ENV: production
            FLASK_DEBUG: 0
        image: openvida-manage
        stdin_open: true
        tty: true
        <<: *default_volumes

volumes:
    sqlserverdata:
