x-build-args: &build_args
    INSTALL_PYTHON_VERSION: "3.13.3"

x-default-volumes: &default_volumes
    volumes:
        - ./:/app
        - C:/VIDA/jboss/standalone/deployments/VidaEar.ear/VidaWeb.war/WEB-INF/classes:/xsl

x-db-paths: &db_paths
    VIDA_ACCESS_DB_URI: "mssql+pyodbc://vida_flask:vida_flask@localhost/AccessServer?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_BASEDATA_DB_URI: "mssql+pyodbc://vida_flask:vida_flask@localhost/basedata?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_CARCOM_DB_URI: "mssql+pyodbc://vida_flask:vida_flask@localhost/carcom?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_DIAG_DB_URI: "mssql+pyodbc://vida_flask:vida_flask@localhost/DiagSwdlRepository?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_SESSION_DB_URI: "mssql+pyodbc://vida_flask:vida_flask@localhost/DiagSwdlSession?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_TIMING_DB_URI: "mssql+pyodbc://vida_flask:vida_flask@localhost/DiceTiming?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_EPC_DB_URI: "mssql+pyodbc://vida_flask:vida_flask@localhost/epc?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_IMAGES_DB_URI: "mssql+pyodbc://vida_flask:vida_flask@localhost/ImageRepository?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_SERVICE_DB_URI: "mssql+pyodbc://vida_flask:vida_flask@localhost/servicerep_en-US?driver=ODBC+Driver+17+for+SQL+Server"
    VIDA_XSL_PATH: /xsl

services:
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: db
        restart: always
        environment:
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433
        volumes:
            - sqlserverdata:/var/opt/mssql
            - C:/VIDA/db:/vida

    flask-dev:
        build:
            context: .
            target: development
            args:
                <<: *build_args
        image: vida_flask-development
        ports:
            - 5000:5000
            - 2992:2992
        environment:
            GUNICORN_WORKERS: 4
            <<: *db_paths
        depends_on:
            - db
        <<: *default_volumes

    flask-prod:
        build:
            context: .
            target: production
            args:
                <<: *build_args
        image: vida_flask-production
        restart: always
        ports:
            - 5000:5000
        environment:
            FLASK_ENV: production
            FLASK_DEBUG: 0
            LOG_LEVEL: info
            GUNICORN_WORKERS: 4
            <<: *db_paths
        depends_on:
            - db
        <<: *default_volumes

    manage:
        build:
            context: .
            target: development
            args:
                <<: *build_args
        entrypoint: flask
        environment:
            FLASK_ENV: production
            FLASK_DEBUG: 0
        image: vida_flask-manage
        stdin_open: true
        tty: true
        <<: *default_volumes

volumes:
    sqlserverdata:
