NON_SELF_CLOSING_TAGS = (
    "div",
    "span",
    "header",
    "footer",
    "section",
    "article",
    "aside",
    "nav",
    "p",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "a",
    "strong",
    "em",
    "blockquote",
    "pre",
    "ul",
    "ol",
    "li",
    "table",
    "tr",
    "td",
    "th",
    "form",
    "button",
    "textarea",
    "select",
    "label",
    "video",
    "audio",
    "iframe",
    "canvas",
    "script",
    "style",
    "title",
)
BOOTSTRAP_CLASSES = (
    ("commonText", ""),
    ("commonBold", "fw-bold"),
    ("commonBoldMarginBottom", "fw-bold mb-2"),
    ("para", "mt-2"),
    ("bigTitle", "h3 fw-bold"),
    ("smallTitle", "h5 fw-bold"),
    ("listTitle", "h5"),
    ("internalLinkClass", "mx-1"),
    ("software", "text-decoration-underline text-primary"),
)
REPLACE_STRINGS = (
    ('<div xmlns:fo="[^"]*" xmlns:html="[^"]*" style="[^"]*">', "<div>"),
    ('<LINK REL="[^"]*" href="[^"]*" TYPE="[^"]*"/>\n', ""),
)
